// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Garage.Core.Models
{
    public partial class Adm_ManageTrigger
    {
        [Key]
        public int ID { get; set; }
       
        [Required(ErrorMessage = "Category is a required field")]
        [Display(Name = "Category")]
        public int? CategoryID { get; set; }

        [Required(ErrorMessage = "Trigger name is a required field")]
        [Display(Name = "Trigger")]
        public int? TriggerID { get; set; }

        [Required(ErrorMessage = "Trigger value is a required field")]
        [Display(Name = "Trigger Value")]
        public int? TriggerValue { get; set; }

        [Required(ErrorMessage = "Threshold is a required field")]
        public int? Threshold { get; set; }

        public bool? IsActive { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedOn { get; set; }
    }
}