// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Garage.Core.Models
{
    public partial class Adm_ManageTrigger
    {
        [Key]
        public int ID { get; set; }

        [Required(ErrorMessage = "Category is required")]
        public int CategoryID { get; set; }

        [Required(ErrorMessage = "Trigger is required")]
        public int TriggerID { get; set; }

        [Required(ErrorMessage = "Trigger value is required")]
        [Range(1,1000000, ErrorMessage = "Enter valid Trigger Value")]
        public int TriggerValue { get; set; }

        [Required(ErrorMessage = "Threshold is required")]
        [Range(1, 1000000, ErrorMessage = "Enter valid Threshold Value")]
        public int Threshold { get; set; }
        public bool? IsActive { get; set; }
        [StringLength(50)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedOn { get; set; }
    }
}