// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Garage.Core.Models
{
    public partial class Adm_MaintenanceType
    {
        [Key]
        public int ID { get; set; }
        [StringLength(30)]
        public string MaintenanceName { get; set; }
    }
}