// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Garage.Core.Models
{
    public partial class Hdr_StatutoryRequirement
    {
        [Key]
        public int ID { get; set; }
        public int AssetID { get; set; }
        [StringLength(25)]
        public string RegNo { get; set; }
        [StringLength(25)]
        public string ChassisNo { get; set; }
        public int? StatutoryID { get; set; }
        public bool? StatutoryAvailable { get; set; }
        public int? InsuranceTypeID { get; set; }
        [StringLength(50)]
        public string InsuranceCompany { get; set; }
        public double? AmountPaid { get; set; }
        [DataType(DataType.Date)]
        public DateTime? DateFrom { get; set; }

        [DataType(DataType.Date)]
        public DateTime? DateTo { get; set; }
        [StringLength(255)]
        public string FileName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateModified { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
    }
}