// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace Garage.Core.Models
{
    public partial class Trn_LogSheet
    {
        [Key]
        public int ID { get; set; }
        public int? CategoryID { get; set; }
        public int? LogTypeID { get; set; }
        public int? TriggerID { get; set; }
        public int? FrequencyID { get; set; }
        public int? AssetID { get; set; }
        [StringLength(10)]
        public string RegNo { get; set; }
        public double? PreviousValue { get; set; }
        public double? CurrentValue { get; set; }
        public int? LogStatus { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ModifiedOn { get; set; }
        [StringLength(50)]
        public string ModifiedBy { get; set; }
        public string DriverName { get; set; }
        public string Passengers { get; set; }
    }
}